let atendimentos=[];
async function carregarAtendimentos(){atendimentos=await buscarTodos("atendimentos");return atendimentos}
function converterParaMinutos(h){const p=h.split(":");return Number(p[0])*60+Number(p[1])}
function minutosParaHorario(m){return String(Math.floor(m/60)).padStart(2,"0")+":"+String(m%60).padStart(2,"0")}
function horariosSeSobrepoem(a,da,b,db){return a<b+db&&a+da>b}
function horarioEstaLivre(data,horario,duracao){const i=converterParaMinutos(horario);return !atendimentos.some(a=>a.data===data&&a.status!=="cancelado"&&horariosSeSobrepoem(i,Number(duracao),converterParaMinutos(a.horario),Number(a.duracao)||60))}
function calcularHorariosDisponiveis({data,abertura="06:00",fechamento="20:00",intervaloInicio="12:00",intervaloFim="13:00",duracao=60,passo=30}){const r=[],ini=converterParaMinutos(abertura),fim=converterParaMinutos(fechamento),ii=converterParaMinutos(intervaloInicio),fi=converterParaMinutos(intervaloFim);for(let m=ini;m+Number(duracao)<=fim;m+=Number(passo)){if(m<fi&&m+Number(duracao)>ii)continue;const h=minutosParaHorario(m);if(horarioEstaLivre(data,h,duracao))r.push(h)}return r}
async function criarAtendimento(d){const c=clientePorId(d.clienteId);if(!c)throw Error("Cliente não encontrada.");const a={id:d.id?Number(d.id):undefined,clienteId:c.id,cliente:c.nome,telefone:c.telefone,data:d.data,horario:d.horario,servico:d.servico||c.servico||"Atendimento",duracao:Number(d.duracao||c.duracao||60),status:"agendado"};if(!horarioEstaLivre(a.data,a.horario,a.duracao))throw Error("Esse horário não está disponível.");const id=await salvarRegistro("atendimentos",a);await carregarAtendimentos();return id}
async function finalizarAtendimento(id){const a=atendimentos.find(x=>Number(x.id)===Number(id));if(!a)return;a.status="atendido";await salvarRegistro("atendimentos",a);const c=clientePorId(a.clienteId);if(c){c.ultimoAtendimento=a.data;if(c.recorrente==="sim"&&c.frequencia)c.proximoAtendimento=calcularProximoAtendimento(a.data,c.frequencia);await salvarRegistro("clientes",c)}await carregarAtendimentos();await carregarClientes();renderizarTudo()}
async function cancelarAtendimento(id){const a=atendimentos.find(x=>Number(x.id)===Number(id));if(!a)return;a.status="cancelado";await salvarRegistro("atendimentos",a);await carregarAtendimentos();renderizarTudo()}