document.addEventListener("DOMContentLoaded",iniciarAplicacao);
async function iniciarAplicacao(){await abrirBanco();await carregarClientes();await carregarAtendimentos();configurarEventos();renderizarTudo();if("serviceWorker"in navigator)navigator.serviceWorker.register("service-worker.js").catch(console.error)}
function configurarEventos(){document.getElementById("btnVoz").onclick=iniciarVoz;document.getElementById("btnNovaCliente").onclick=()=>abrirModalCliente();document.getElementById("btnNovoAgendamento").onclick=()=>abrirModalAgendamento();document.getElementById("formCliente").onsubmit=salvarClienteFormulario;document.getElementById("formAgendamento").onsubmit=salvarAgendamentoFormulario;document.getElementById("clienteRecorrente").onchange=controlarFrequencia;document.getElementById("buscarCliente").oninput=renderizarClientes}
function formatarData(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function formatarDataBR(d){if(!d)return"-";const p=d.split("-");return`${p[2]}/${p[1]}/${p[0]}`}
function dataHoje(){return formatarData(new Date())}
function renderizarTudo(){renderizarData();renderizarAtencao();renderizarHoje();renderizarClientes();atualizarHorariosDisponiveis();preencherClientesAgendamento()}
function renderizarData(){document.getElementById("dataAtual").textContent=new Date().toLocaleDateString("pt-BR",{weekday:"long",day:"numeric",month:"long"})}
function renderizarAtencao(){const s=document.getElementById("secaoAtencao"),l=document.getElementById("listaAtencao"),a=obterAtencoes();if(!a.length){s.classList.add("oculto");return}s.classList.remove("oculto");l.innerHTML=a.map(x=>`<div class="atencao-item">${x.tipo==="aniversario"?"🎂":"🔄"} ${x.texto}${x.tipo==="aniversario"?`<br><button class="item-acoes" onclick="mensagemAniversario(${x.cliente.id})">💬 Mensagem</button>`:""}</div>`).join("")}
function renderizarHoje(){const h=dataHoje(),l=document.getElementById("listaHoje"),a=atendimentos.filter(x=>x.data===h&&x.status!=="cancelado").sort((a,b)=>a.horario.localeCompare(b.horario));document.getElementById("totalHoje").textContent=a.length;if(!a.length){l.innerHTML='<div class="vazio">Nenhum atendimento hoje.</div>';return}l.innerHTML=a.map(x=>`<div class="item"><span class="horario">${x.horario}</span><strong>${x.cliente}</strong><small>${x.servico}</small><div class="item-acoes">${x.status==="agendado"?`<button onclick="finalizarAtendimento(${x.id})">✓ Atendido</button><button onclick="cancelarAtendimento(${x.id})">Cancelar</button>`:`<small>${x.status}</small>`}</div></div>`).join("")}
function atualizarHorariosDisponiveis(){const l=document.getElementById("listaHorarios"),h=calcularHorariosDisponiveis({data:dataHoje()});l.innerHTML=h.map(x=>`<button class="horario-disponivel" onclick="abrirAgendamentoComHorario('${x}')">${x}</button>`).join("")}
function renderizarClientes(){const l=document.getElementById("listaClientes"),b=normalizarTexto(document.getElementById("buscarCliente").value),a=clientes.filter(c=>!b||normalizarTexto(c.nome).includes(b));if(!a.length){l.innerHTML='<div class="vazio">Nenhuma cliente encontrada.</div>';return}l.innerHTML=a.map(c=>`<div class="item" onclick="abrirEdicaoCliente(${c.id})"><strong>${c.nome}</strong><small>${c.recorrente==="sim"?`🔄 A cada ${c.frequencia} dias`:"Cliente esporádica"}</small><br><small>${c.proximoAtendimento?`Próximo: ${formatarDataBR(c.proximoAtendimento)}`:""}${c.dataNascimento?` · 🎂 ${formatarDataBR(c.dataNascimento)}`:""}</small></div>`).join("")}
function controlarFrequencia(){document.getElementById("campoFrequencia").classList.toggle("oculto",document.getElementById("clienteRecorrente").value!=="sim")}
function abrirModalCliente(c=null){document.getElementById("modalCliente").classList.remove("oculto");document.getElementById("tituloModalCliente").textContent=c?"Editar cliente":"Nova cliente";document.getElementById("clienteId").value=c?.id||"";document.getElementById("clienteNome").value=c?.nome||"";document.getElementById("clienteTelefone").value=c?.telefone||"";document.getElementById("clienteNascimento").value=c?.dataNascimento||"";document.getElementById("clienteServico").value=c?.servico||"";document.getElementById("clienteDuracao").value=c?.duracao||60;document.getElementById("clienteRecorrente").value=c?.recorrente||"nao";document.getElementById("clienteFrequencia").value=c?.frequencia||15;controlarFrequencia()}
function abrirEdicaoCliente(id){abrirModalCliente(clientePorId(id))}
function fecharModalCliente(){document.getElementById("modalCliente").classList.add("oculto")}
async function salvarClienteFormulario(e){e.preventDefault();const id=document.getElementById("clienteId").value,old=id?clientePorId(id):null;await salvarCliente({id:id?Number(id):undefined,nome:document.getElementById("clienteNome").value,telefone:document.getElementById("clienteTelefone").value,dataNascimento:document.getElementById("clienteNascimento").value,servico:document.getElementById("clienteServico").value,duracao:document.getElementById("clienteDuracao").value,recorrente:document.getElementById("clienteRecorrente").value,frequencia:document.getElementById("clienteFrequencia").value,ultimoAtendimento:old?.ultimoAtendimento,proximoAtendimento:old?.proximoAtendimento});fecharModalCliente();renderizarTudo()}
function abrirModalAgendamento(){preencherClientesAgendamento();document.getElementById("agendamentoData").value=dataHoje();document.getElementById("modalAgendamento").classList.remove("oculto");atualizarHorariosModal()}
function fecharModalAgendamento(){document.getElementById("modalAgendamento").classList.add("oculto")}
function preencherClientesAgendamento(){document.getElementById("agendamentoCliente").innerHTML='<option value="">Selecione a cliente</option>'+clientes.slice().sort((a,b)=>a.nome.localeCompare(b.nome)).map(c=>`<option value="${c.id}">${c.nome}</option>`).join("")}
function atualizarHorariosModal(){const id=Number(document.getElementById("agendamentoCliente").value),d=document.getElementById("agendamentoData").value,c=clientePorId(id),h=calcularHorariosDisponiveis({data:d,duracao:c?.duracao||60}),s=document.getElementById("agendamentoHorario");s.innerHTML=h.map(x=>`<option value="${x}">${x}</option>`).join("");if(c)document.getElementById("agendamentoServico").value=c.servico||""}
function abrirAgendamentoComHorario(h){abrirModalAgendamento();document.getElementById("agendamentoHorario").value=h}
function abrirAgendamentoComDados(c,d,h){abrirModalAgendamento();document.getElementById("agendamentoCliente").value=c.id;document.getElementById("agendamentoData").value=d;document.getElementById("agendamentoServico").value=c.servico||"";atualizarHorariosModal();if(h)document.getElementById("agendamentoHorario").value=h}
async function salvarAgendamentoFormulario(e){e.preventDefault();try{await criarAtendimento({clienteId:Number(document.getElementById("agendamentoCliente").value),data:document.getElementById("agendamentoData").value,horario:document.getElementById("agendamentoHorario").value,servico:document.getElementById("agendamentoServico").value});fecharModalAgendamento();renderizarTudo()}catch(err){alert(err.message)}}
function mensagemAniversario(id){const c=clientePorId(id);if(!c)return;const msg=`Oi, ${c.nome}! 💕 Passando para desejar um feliz aniversário! Que seu novo ciclo seja maravilhoso, cheio de saúde, alegria e muitas conquistas. Espero te ver em breve! 🎂✨`;const tel=c.telefone.replace(/\D/g,"");if(!tel){navigator.clipboard?.writeText(msg);alert("A mensagem foi copiada. Cadastre o telefone para abrir o WhatsApp diretamente.");return}window.open("https://wa.me/"+tel+"?text="+encodeURIComponent(msg),"_blank")}
document.getElementById("agendamentoCliente").addEventListener("change",atualizarHorariosModal);document.getElementById("agendamentoData").addEventListener("change",atualizarHorariosModal)